-- CampusHub Oracle Database Schema
-- Run this script as the designated application user (e.g., c##campus_admin)

-- Drop existing tables to ensure a clean slate
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE volunteer_tasks CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE registrations CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE events CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE students CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- ==========================================
-- 1. STUDENTS TABLE
-- ==========================================
-- Note: 'user_id' refers to the Django auth_user table. In a standalone schema,
-- this would link to the users table. Here it is maintained for architectural parity.
CREATE TABLE students (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL UNIQUE,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(254) NOT NULL UNIQUE,
    phone VARCHAR2(20) NOT NULL,
    course VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==========================================
-- 2. EVENTS TABLE
-- ==========================================
CREATE TABLE events (
    event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    event_date TIMESTAMP NOT NULL,
    location VARCHAR2(255) NOT NULL,
    capacity NUMBER NOT NULL,
    status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT capacity_positive CHECK (capacity > 0),
    CONSTRAINT events_status_chk CHECK (status IN ('OPEN', 'CLOSED', 'COMPLETED', 'CANCELLED'))
);

-- ==========================================
-- 3. REGISTRATIONS TABLE
-- ==========================================
CREATE TABLE registrations (
    registration_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL,
    event_id NUMBER NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT fk_registration_student FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE,
    CONSTRAINT fk_registration_event FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,
    CONSTRAINT unique_student_event_registration UNIQUE (student_id, event_id),
    CONSTRAINT reg_status_chk CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED'))
);

-- ==========================================
-- 4. VOLUNTEER_TASKS TABLE
-- ==========================================
CREATE TABLE volunteer_tasks (
    task_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id NUMBER NOT NULL,
    student_id NUMBER NOT NULL,
    task_name VARCHAR2(255) NOT NULL,
    task_status VARCHAR2(20) DEFAULT 'ASSIGNED' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT fk_task_event FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,
    CONSTRAINT fk_task_student FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE,
    CONSTRAINT task_status_chk CHECK (task_status IN ('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
);

-- End of schema
